version: "3.9"
services:
  database:
    image: postgres:14.5
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: cloudsqliamuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bidrag-behandling
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local