apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each azure_access_inbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
      {{/each}}
    outbound:
      external:
      {{#each outbound-access-hosts}}
          - host: {{this}}
      {{/each}}
      rules:
      {{#each outbound-access-apps}}
          - application: {{this}}
      {{/each}}
  secureLogs:
    enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      memory: 1500Mi
      cpu: 1000m
    requests:
      memory: 1028Mi
      cpu: 100m
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  kafka:
    pool: {{ kafka.pool }}
  gcp:
    sqlInstances:
      - name: {{ database.dbname }}
        type: POSTGRES_15
        diskAutoresize: {{ database.autoResize }}
        tier: {{ database.tier }}
        databases:
          - name: bidrag-behandling
            envVarPrefix: DB
