name: bidrag-behandling
ingresses:
  - https://bidrag-behandling.intern.nav.no
env:
  BIDRAG_BEREGN_FORSKUDD_URL: http://bidrag-beregn-forskudd-rest
  BIDRAG_BEREGN_FORSKUDD_SCOPE: prod-gcp.bidrag.bidrag-beregn-forskudd-rest
  BIDRAG_GRUNNLAG_URL: http://bidrag-grunnlag
  BIDRAG_GRUNNLAG_URL_SCOPE: prod-gcp.bidrag.bidrag-grunnlag
  BIDRAG_FORSENDELSE_URL: http://bidrag-dokument-forsendelse
  BIDRAG_FORSENDELSE_SCOPE: prod-gcp.bidrag.bidrag-dokument-forsendelse
  BIDRAG_TILGANGSKONTROLL_URL: http://bidrag-tilgangskontroll
  BIDRAG_TILGANGGSKONTROLL_SCOPE: prod-gcp.bidrag.bidrag-tilgangskontroll
  TOPIC_VEDTAK: bidrag.vedtak
kafka:
  pool: nav-prod
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-dokument-forsendelse
    namespace: bidrag
    cluster: prod-gcp
database:
  dbname: bidrag-behandling
  autoResize: false
  tier: db-custom-1-3840
outbound-access-apps:
  - bidrag-beregn-forskudd-rest
  - bidrag-grunnlag
  - bidrag-dokument-forsendelse
  - bidrag-tilgangskontroll