name: bidrag-behandling
ingresses:
  - https://bidrag-behandling.intern.nav.no
min_replicas: 2
env:
  SPRING_PROFILES_ACTIVE: live,nais,database-legacy
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
#kafka:
#  pool: nav-prod
#azure_access_inbound:
#  - application: bidrag-ui
#    namespace: bidrag
#    cluster: prod-fss
#database:
#  dbname: bidrag-behandling
#  autoResize: true
#  tier: db-custom-1-3840
#outbound-access-apps:
#  - bidrag-grunnlag
#outbound-access-hosts:
#  - bidrag-dokument.prod-fss-pub.nais.io
#unleash:
#  env: development
#  secret_name: bidrag-behandling-unleash-api-token