name: bidrag-behandling
ingresses:
  - https://bidrag-behandling.intern.nav.no
env:
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_BEREGN_FORSKUDD_URL: http://bidrag-beregn-forskudd-rest
  BIDRAG_BEREGN_FORSKUDD_SCOPE: prod-gcp.bidrag.bidrag-beregn-forskudd-rest
  BIDRAG_GRUNNLAG_URL: http://bidrag-grunnlag
  BIDRAG_GRUNNLAG_SCOPE: prod-gcp.bidrag.bidrag-grunnlag
  BIDRAG_FORSENDELSE_URL: http://bidrag-dokument-forsendelse
  BIDRAG_FORSENDELSE_SCOPE: prod-gcp.bidrag.bidrag-dokument-forsendelse
  BIDRAG_TILGANGSKONTROLL_URL: http://bidrag-tilgangskontroll
  BIDRAG_TILGANGGSKONTROLL_SCOPE: prod-gcp.bidrag.bidrag-tilgangskontroll
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  ARBEID_OG_INNTEKT_URL: https://arbeid-og-inntekt.prod-fss-pub.nais.io/api/v2
  TOPIC_VEDTAK: bidrag.vedtak
kafka:
  pool: nav-prod
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-dokument-forsendelse
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-dokument-bestilling
    namespace: bidrag
    cluster: prod-gcp
database:
  dbname: bidrag-behandling
  autoResize: true
  tier: db-custom-1-3840
outbound-access-apps:
  - bidrag-beregn-forskudd-rest
  - bidrag-grunnlag
  - bidrag-dokument-forsendelse
  - bidrag-tilgangskontroll
outbound-access-hosts:
  - bidrag-person.prod-fss-pub.nais.io
  - bidrag-organisasjon.prod-fss-pub.nais.io
  - bidrag-sjablon.prod-fss-pub.nais.io
  - arbeid-og-inntekt.prod-fss-pub.nais.io
unleash:
  env: development
  secret_name: bidrag-behandling-unleash-api-token