name: bidrag-behandling
ingresses:
  - https://bidrag-behandling.intern.nav.no
env:
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_GRUNNLAG_URL: http://bidrag-grunnlag
  BIDRAG_GRUNNLAG_SCOPE: prod-gcp.bidrag.bidrag-grunnlag
  BIDRAG_FORSENDELSE_URL: http://bidrag-dokument-forsendelse
  BIDRAG_FORSENDELSE_SCOPE: prod-gcp.bidrag.bidrag-dokument-forsendelse
  BIDRAG_TILGANGSKONTROLL_URL: http://bidrag-tilgangskontroll
  BIDRAG_TILGANGGSKONTROLL_SCOPE: prod-gcp.bidrag.bidrag-tilgangskontroll
  BIDRAG_STONAD_URL: http://bidrag-stonad
  BIDRAG_STONAD_SCOPE: prod-gcp.bidrag.bidrag-stonad
  BIDRAG_VEDTAK_URL: http://bidrag-vedtak
  BIDRAG_VEDTAK_SCOPE: prod-gcp.bidrag.bidrag-vedtak
  BIDRAG_BBM_URL: https://bidrag-bbm.prod-fss-pub.nais.io
  BIDRAG_BBM_SCOPE: prod-fss.bidrag.bidrag-bbm
  BIDRAG_DOKUMENT_PRODUKSJON_URL: http://bidrag-dokument-produksjon
  BIDRAG_DOKUMENT_PRODUKSJON_SCOPE: prod-gcp.bidrag.bidrag-dokument-produksjon
  BIDRAG_DOKUMENT_URL: https://bidrag-dokument.prod-fss-pub.nais.io/bidrag-dokument
  BIDRAG_DOKUMENT_SCOPE: prod-fss.bidrag.bidrag-dokument
  BIDRAG_SAK_URL: https://bidrag-sak.prod-fss-pub.nais.io/bidrag-sak
  BIDRAG_SAK_SCOPE: prod-fss.bidrag.bidrag-sak
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  ARBEID_OG_INNTEKT_URL: https://arbeid-og-inntekt.prod-fss-pub.nais.io/api/v2
  GRUNNLAG_MIN_ANT_MINUTTER_SIDEN_FORRIGE_INNHENTING: 600
  KODEVERK_URL: https://kodeverk-api.nav.no
  TOPIC_VEDTAK: bidrag.vedtak
kafka:
  pool: nav-prod
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-dokument-forsendelse
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-dokument-bestilling
    namespace: bidrag
    cluster: prod-gcp
database:
  dbname: bidrag-behandling
  autoResize: true
  tier: db-custom-1-3840
outbound-access-apps:
  - bidrag-grunnlag
  - bidrag-stonad
  - bidrag-dokument-forsendelse
  - bidrag-tilgangskontroll
  - bidrag-vedtak
  - bidrag-dokument-produksjon
outbound-access-hosts:
  - bidrag-dokument.prod-fss-pub.nais.io
  - bidrag-person.prod-fss-pub.nais.io
  - bidrag-organisasjon.prod-fss-pub.nais.io
  - bidrag-sjablon.prod-fss-pub.nais.io
  - arbeid-og-inntekt.prod-fss-pub.nais.io
  - bidrag-unleash-api.nav.cloud.nais.io
  - kodeverk-api.nav.no
  - bidrag-bbm.prod-fss-pub.nais.io
unleash:
  env: development
  secret_name: bidrag-behandling-unleash-api-token