-- Table: INNTEKT, INNTEKT_POST

/*
     Slettede data må evnt hentes fra backup

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.39';
 */

DELETE FROM INNTEKT_POST WHERE INNTEKT_ID IN (
    SELECT I.ID FROM INNTEKT I WHERE I.INNTEKT_TYPE IS NULL
);

DELETE FROM INNTEKT I WHERE I.INNTEKT_TYPE IS NULL;






