CREATE TYPE SOKNAD_FRA_TYPE AS ENUM
(
    'BM_I_ANNEN_SAK',
    'BARN_18',
    'TK',
    'FTK',
    'FYLKESNEMDA',
    'KONVERTERING',
    'BM',
    'NORSKE_MYNDIGH',
    'BP',
    'TI',
    'UTENLANDSKE_MYNDIGH',
    'VERGE',
    'KOMMUNE'
);

CREATE CAST (VARCHAR AS SOKNAD_FRA_TYPE) WITH INOUT AS IMPLICIT;

ALTER TABLE BEHANDLING
    ADD COLUMN MOTTAT_DATO DATE DEFAULT NOW(),
    ADD COLUMN SOKNAD_FRA SOKNAD_FRA_TYPE DEFAULT 'BM';

ALTER TABLE BEHANDLING
    ALTER COLUMN MOTTAT_DATO SET NOT NULL;

ALTER TABLE BEHANDLING
    ALTER COLUMN SOKNAD_FRA SET NOT NULL;