-- Tables: BARN_I_HUSSTAND & BARN_I_HUSSTAND_PERIODE

/*
    Slettede data må evnt gjenopprettes fra backup

    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.46';
 */

DELETE FROM BARN_I_HUSSTAND_PERIODE WHERE BARN_I_HUSSTAND_ID IN (
    SELECT ID FROM BARN_I_HUSSTAND WHERE FOEDSELSDATO IS NULL);

DELETE FROM BARN_I_HUSSTAND WHERE FOEDSELSDATO IS NULL;








