ALTER TABLE BEHANDLING
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE ROLLE
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE NOT NULL;

CREATE RULE BEHANDLING_PROTECT AS ON DELETE TO BEHANDLING DO INSTEAD NOTHING;
CREATE RULE ROLLE_PROTECT AS ON DELETE TO ROLLE DO INSTEAD NOTHING;