-- Table: SIVILSTAND

/*
     ALTER TABLE SIVILSTAND RENAME COLUMN SIVILSTANDSTYPE TO SIVILSTAND_TYPE;

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.36';
 */

ALTER TABLE SIVILSTAND RENAME COLUMN SIVILSTAND_TYPE TO SIVILSTANDSTYPE;





