ALTER TABLE BEHANDLING
    ALTER COLUMN AARSAK TYPE TEXT;

ALTER TABLE BEHANDLING
    DROP COLUMN AVSLAG;

DROP TYPE FORSKUDD_BEREGNING_KODE_AARSAK_TYPE CASCADE;

ALTER TABLE BEHANDLING_BARN
    RENAME TO BARN_I_HUSSTAND;

ALTER TABLE BEHANDLING_BARN_PERIODE
    RENAME TO BARN_I_HUSSTAND_PERIODE;