-- Table: OPPLYSNINGER => GRUNNLAG

/* -- Rollback --

  ALTER TABLE GRUNNLAG RENAME COLUMN TYPE TO OPPLYSNINGER_TYPE;
  ALTER TABLE GRUNNLAG ALTER COLUMN INNHENTET TYPE DATE;
  ALTER TABLE GRUNNLAG RENAME COLUMN INNHENTET TO HENTET_DATO;
  ALTER TABLE GRUNNLAG ADD COLUMN IF NOT EXISTS TS timestamp DEFAULT now() NOT NULL;
  ALTER TABLE GRUNNLAG RENAME TO OPPLYSNINGER;

  DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.50';

 */

ALTER TABLE OPPLYSNINGER RENAME COLUMN OPPLYSNINGER_TYPE TO TYPE;
ALTER TABLE OPPLYSNINGER ALTER COLUMN HENTET_DATO TYPE TIMESTAMP;
ALTER TABLE OPPLYSNINGER ALTER COLUMN HENTET_DATO SET DEFAULT now();
ALTER TABLE OPPLYSNINGER RENAME COLUMN HENTET_DATO TO INNHENTET;
ALTER TABLE OPPLYSNINGER DROP COLUMN TS;
ALTER TABLE OPPLYSNINGER ALTER COLUMN DATA TYPE jsonb USING DATA::Jsonb;
ALTER TABLE OPPLYSNINGER RENAME TO GRUNNLAG;
