ALTER TABLE BEHANDLING
    ADD COLUMN SOKNAD_ID INT not null default -1;
ALTER TABLE BEHANDLING
    ADD COLUMN SOKNAD_REF_ID INT;
ALTER TABLE BEHANDLING
    ADD COLUMN OPPRETTET_TIDSPUNKT timestamp DEFAULT now() NOT NULL;