alter type SIVILSTAND_TYPE rename to SIVILSTAND_TYPE_OLD;

CREATE TYPE SIVILSTAND_TYPE AS ENUM
    (
        'BOR_ALENE_MED_BARN',
        'GIFT'
    );

CREATE CAST (VARCHAR AS SIVILSTAND_TYPE) WITH INOUT AS IMPLICIT;
alter table SIVILSTAND rename column SIVILSTAND_TYPE to SIVILSTAND_TYPE_OLD;

ALTER TABLE SIVILSTAND
    ADD COLUMN SIVILSTAND_TYPE SIVILSTAND_TYPE DEFAULT 'BOR_ALENE_MED_BARN' not null ;
update SIVILSTAND set SIVILSTAND_TYPE = 'BOR_ALENE_MED_BARN' where SIVILSTAND_TYPE_OLD != 'GIFT';

ALTER TABLE SIVILSTAND DROP COLUMN IF EXISTS SIVILSTAND_TYPE_OLD cascade;
drop type SIVILSTAND_TYPE_OLD cascade;