/*
 DB-skjema baseline per 19.01.2024

 DDL er hentet med:
 >pg_dump --schema-only --no-owner --no-privileges -U cloudsqliamuser -F t bidrag-behandling | gzip >behandling_dump-$(date +%Y-%m-%d).tar.gz

 */


CREATE TYPE public.avslag_type AS ENUM (
    'ANNET_AVSLAG',
    'PGA_BARNEPENSJ',
    'BARNS_EKTESKAP',
    'BARNS_INNTEKT',
    'PGA_YTELSE_FTRL',
    'FULLT_UNDERH_OFF',
    'IKKE_OMSORG',
    'IKKE_OPPH_I_RIKET',
    'MANGL_DOK',
    'PGA_SAMMENFL',
    'OPPH_UTLAND',
    'UTENL_YTELSE'
    );


--
-- Name: soknad_fra_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.soknad_fra_type AS ENUM (
    'BM_I_ANNEN_SAK',
    'BARN_18_AAR',
    'NAV_BIDRAG',
    'FYLKESNEMDA',
    'NAV_INTERNASJONAL',
    'KOMMUNE',
    'KONVERTERING',
    'BIDRAGSMOTTAKER',
    'NORSKE_MYNDIGHET',
    'BIDRAGSPLIKTIG',
    'UTENLANDSKE_MYNDIGHET',
    'VERGE',
    'TRYGDEETATEN_INNKREVING',
    'KLAGE_ANKE'
    );


--
-- Name: CAST (character varying AS public.avslag_type); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.avslag_type) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (character varying AS public.soknad_fra_type); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.soknad_fra_type) WITH INOUT AS IMPLICIT;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: barn_i_husstand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.barn_i_husstand (
                                        id bigint NOT NULL,
                                        behandling_id bigint NOT NULL,
                                        med_i_saken boolean,
                                        ident character varying(20),
                                        navn text,
                                        foedselsdato date NOT NULL
);


--
-- Name: barn_i_husstand_periode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.barn_i_husstand_periode (
                                                id bigint NOT NULL,
                                                barn_i_husstand_id bigint NOT NULL,
                                                dato_fom date,
                                                dato_tom date,
                                                kilde text,
                                                bostatus text DEFAULT 'MED_FORELDER'::text NOT NULL
);


--
-- Name: behandling; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.behandling (
                                   id bigint NOT NULL,
                                   virkningsdato date,
                                   aarsak text,
                                   dato_fom date,
                                   dato_tom date,
                                   saksnummer character varying(7),
                                   behandler_enhet character(4),
                                   mottattdato date DEFAULT now() NOT NULL,
                                   virkningstidspunktbegrunnelse_vedtak_og_notat text,
                                   virkningstidspunktbegrunnelse_kun_notat text,
                                   boforholdsbegrunnelse_vedtak_og_notat text,
                                   boforholdsbegrunnelse_kun_notat text,
                                   inntektsbegrunnelse_vedtak_og_notat text,
                                   inntektsbegrunnelse_kun_notat text,
                                   vedtakstype text DEFAULT (NOT NULL::boolean),
                                   soknad_fra public.soknad_fra_type DEFAULT 'BIDRAGSMOTTAKER'::public.soknad_fra_type NOT NULL,
                                   stonadstype text,
                                   engangsbeloptype text,
                                   vedtaksid bigint,
                                   soknadsid bigint DEFAULT '-1'::integer NOT NULL,
                                   soknad_ref_id bigint,
                                   opprettet_tidspunkt timestamp without time zone DEFAULT now() NOT NULL,
                                   deleted boolean DEFAULT false NOT NULL,
                                   grunnlagspakkeid bigint,
                                   opprettet_av text DEFAULT ''::text NOT NULL,
                                   opprettet_av_navn text,
                                   kildeapplikasjon text DEFAULT 'bisys'::text NOT NULL,
                                   grunnlag_sist_innhentet timestamp without time zone
);


--
-- Name: behandling_barn_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.barn_i_husstand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.behandling_barn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: behandling_barn_periode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.barn_i_husstand_periode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.behandling_barn_periode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: behandling_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.behandling ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.behandling_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

--
-- Name: grunnlag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grunnlag (
                                 id bigint NOT NULL,
                                 behandling_id bigint NOT NULL,
                                 data jsonb,
                                 innhentet timestamp without time zone DEFAULT now(),
                                 type text,
                                 aktiv timestamp without time zone
);


--
-- Name: inntekt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inntekt (
                                id bigint NOT NULL,
                                behandling_id bigint NOT NULL,
                                ta_med boolean NOT NULL,
                                inntektsrapportering text,
                                dato_fom date,
                                dato_tom date,
                                ident text NOT NULL,
                                belop numeric DEFAULT 0 NOT NULL,
                                kilde character varying(15),
                                gjelder_barn character varying(11),
                                opprinnelig_fom date,
                                opprinnelig_tom date
);


--
-- Name: inntekt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inntekt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inntekt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: inntektspost; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inntektspost (
                                     id bigint NOT NULL,
                                     inntekt_id bigint NOT NULL,
                                     belop numeric DEFAULT 0 NOT NULL,
                                     kode text,
                                     visningsnavn text,
                                     inntektstype character varying(50)
);


--
-- Name: inntekt_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inntektspost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inntekt_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: opplysninger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grunnlag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opplysninger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: rolle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rolle (
                              id bigint NOT NULL,
                              ident character varying(20),
                              opprettet timestamp without time zone,
                              behandling_id bigint NOT NULL,
                              foedselsdato date,
                              rolletype text,
                              deleted boolean DEFAULT false NOT NULL,
                              navn character varying(200)
);


--
-- Name: rolle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rolle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rolle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: sivilstand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sivilstand (
                                   id bigint NOT NULL,
                                   behandling_id bigint NOT NULL,
                                   dato_fom date,
                                   dato_tom date,
                                   kilde character varying(25),
                                   sivilstand text
);


--
-- Name: sivilstand_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sivilstand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sivilstand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: barn_i_husstand_periode behandling_barn_periode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.barn_i_husstand_periode
    ADD CONSTRAINT behandling_barn_periode_pkey PRIMARY KEY (id);


--
-- Name: barn_i_husstand behandling_barn_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.barn_i_husstand
    ADD CONSTRAINT behandling_barn_pkey PRIMARY KEY (id);


--
-- Name: behandling behandling_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.behandling
    ADD CONSTRAINT behandling_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: inntekt inntekt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inntekt
    ADD CONSTRAINT inntekt_pkey PRIMARY KEY (id);


--
-- Name: inntektspost inntekt_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inntektspost
    ADD CONSTRAINT inntekt_post_pkey PRIMARY KEY (id);


--
-- Name: grunnlag opplysninger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grunnlag
    ADD CONSTRAINT opplysninger_pkey PRIMARY KEY (id);


--
-- Name: rolle rolle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolle
    ADD CONSTRAINT rolle_pkey PRIMARY KEY (id);


--
-- Name: sivilstand sivilstand_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sivilstand
    ADD CONSTRAINT sivilstand_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: behandling behandling_protect; Type: RULE; Schema: public; Owner: -
--

CREATE RULE behandling_protect AS
    ON DELETE TO public.behandling DO INSTEAD NOTHING;


--
-- Name: rolle rolle_protect; Type: RULE; Schema: public; Owner: -
--

CREATE RULE rolle_protect AS
    ON DELETE TO public.rolle DO INSTEAD NOTHING;


--
-- Name: barn_i_husstand_periode fk_barn_i_husstand_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.barn_i_husstand_periode
    ADD CONSTRAINT fk_barn_i_husstand_id FOREIGN KEY (barn_i_husstand_id) REFERENCES public.barn_i_husstand(id);


--
-- Name: barn_i_husstand fk_behandling_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.barn_i_husstand
    ADD CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES public.behandling(id);


--
-- Name: grunnlag fk_behandling_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grunnlag
    ADD CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES public.behandling(id);


--
-- Name: inntekt fk_behandling_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inntekt
    ADD CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES public.behandling(id);


--
-- Name: rolle fk_behandling_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolle
    ADD CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES public.behandling(id);


--
-- Name: sivilstand fk_behandling_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sivilstand
    ADD CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES public.behandling(id);


--
-- Name: inntektspost fk_inntekt_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inntektspost
    ADD CONSTRAINT fk_inntekt_id FOREIGN KEY (inntekt_id) REFERENCES public.inntekt(id);


--
-- PostgreSQL database dump complete
--