-- Table: ROLLE

/*
    ALTER TABLE ROLLE RENAME COLUMN FOEDSELSDATO TO FODT_DATO;
    ALTER TABLE ROLLE RENAME COLUMN ROLLETYPE TO ROLLE_TYPE;

    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.43';
 */

ALTER TABLE ROLLE RENAME COLUMN FODT_DATO TO FOEDSELSDATO;
ALTER TABLE ROLLE RENAME COLUMN ROLLE_TYPE TO ROLLETYPE;








