ALTER TABLE BARN_I_HUSSTAND_PERIODE
    RENAME COLUMN BEHANDLING_BARN_ID TO BARN_I_HUSSTAND_ID;

ALTER TABLE BARN_I_HUSSTAND_PERIODE
    DROP CONSTRAINT FK_BEHANDLING_BARN_ID;
ALTER TABLE BARN_I_HUSSTAND_PERIODE
    ADD CONSTRAINT FK_BARN_I_HUSSTAND_ID FOREIGN KEY (BARN_I_HUSSTAND_ID)
    REFERENCES BARN_I_HUSSTAND (ID) MATCH SIMPLE;
