-- Table: INNTEKT_POST => INNTEKTSPOST

/*
     ALTER TABLE INNTEKTSPOST RENAME TO INNTEKT_POST;

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.41';
 */

ALTER TABLE INNTEKT_POST RENAME TO INNTEKTSPOST;





