ALTER TABLE ROLLE
    ADD COLUMN NEW_ROLLE_TYPE TEXT;

-- COPY ALL
UPDATE ROLLE
    SET NEW_ROLLE_TYPE = ROLLE_TYPE;

-- UPDATE TO NEW VALUES
UPDATE ROLLE
    SET NEW_ROLLE_TYPE = 'BIDRAGSPLIKTIG' WHERE NEW_ROLLE_TYPE = 'BIDRAGS_PLIKTIG';

UPDATE ROLLE
    SET NEW_ROLLE_TYPE = 'BIDRAGSMOTTAKER' WHERE NEW_ROLLE_TYPE = 'BIDRAGS_MOTTAKER';

UPDATE ROLLE
    SET NEW_ROLLE_TYPE = 'REELLMOTTAKER' WHERE NEW_ROLLE_TYPE = 'REELL_MOTTAKER';


-- DROP OLD COLUMN
ALTER TABLE ROLLE
    DROP COLUMN ROLLE_TYPE;

-- RENAME NEW COLUMN
ALTER TABLE ROLLE
    RENAME COLUMN NEW_ROLLE_TYPE TO ROLLE_TYPE;

-- DROP OLD TYPE
DROP TYPE ROLLE_TYPE CASCADE;