alter type SOKNAD_FRA_TYPE rename to SOKNAD_FRA_TYPE_OLD;

CREATE TYPE SOKNAD_FRA_TYPE AS ENUM
(
    'BM_I_ANNEN_SAK',
    'BARN_18_AAR',
    'NAV_BIDRAG',
    'FYLKESNEMDA',
    'NAV_INTERNASJONAL',
    'KOMMUNE',
    'KONVERTERING',
    'BIDRAGSMOTTAKER',
    'NORSKE_MYNDIGHET',
    'BIDRAGSPLIKTIG',
    'UTENLANDSKE_MYNDIGHET',
    'VERGE',
    'TRYGDEETATEN_INNKREVING',
    'KLAGE_ANKE'
);
CREATE CAST (VARCHAR AS SOKNAD_FRA_TYPE) WITH INOUT AS IMPLICIT;
alter table BEHANDLING rename column SOKNAD_FRA to SOKNAD_FRA_OLD;

ALTER TABLE BEHANDLING
    ADD COLUMN SOKNAD_FRA SOKNAD_FRA_TYPE DEFAULT 'BIDRAGSMOTTAKER' not null ;
update BEHANDLING set SOKNAD_FRA = 'BIDRAGSMOTTAKER' where SOKNAD_FRA_OLD = 'BM';
update BEHANDLING set SOKNAD_FRA = 'BIDRAGSPLIKTIG' where SOKNAD_FRA_OLD = 'BP';
update BEHANDLING set SOKNAD_FRA = 'NAV_BIDRAG' where SOKNAD_FRA_OLD = 'TK';
update BEHANDLING set SOKNAD_FRA = 'KLAGE_ANKE' where SOKNAD_FRA_OLD = 'FTK';
update BEHANDLING set SOKNAD_FRA = 'TRYGDEETATEN_INNKREVING' where SOKNAD_FRA_OLD = 'TI';
update BEHANDLING set SOKNAD_FRA = 'NORSKE_MYNDIGHET' where SOKNAD_FRA_OLD = 'NORSKE_MYNDIGH';
update BEHANDLING set SOKNAD_FRA = 'UTENLANDSKE_MYNDIGHET' where SOKNAD_FRA_OLD = 'UTENLANDSKE_MYNDIGH';
update BEHANDLING set SOKNAD_FRA = 'BARN_18_AAR' where SOKNAD_FRA_OLD = 'BARN_18';

ALTER TABLE BEHANDLING DROP COLUMN IF EXISTS SOKNAD_FRA_OLD cascade;
drop type SOKNAD_FRA_TYPE_OLD cascade;
