-- Table: BARN_I_HUSSTAND_PERIODE

/*
    UPDATE TABLE BARN_I_HUSSTAND_PERIODE
        SET KILDE = 'manuelt' WHERE KILDE  = 'MANUELL';
    UPDATE TABLE BARN_I_HUSSTAND_PERIODE
        SET KILDE = 'offentlig' WHERE KILDE  = 'OFFENTLIG';

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.34';
 */

UPDATE TABLE BARN_I_HUSSTAND_PERIODE
    SET KILDE = 'MANUELL' WHERE KILDE  = 'manuelt';
UPDATE TABLE BARN_I_HUSSTAND_PERIODE
    SET KILDE = 'OFFENTLIG' WHERE KILDE  = 'offentlig' OR KILDE IS NULL;




