-- Table: BARN_I_HUSSTAND

/*
    ALTER TABLE BARN_I_HUSSTAND ALTER COLUMN FOEDSELSDATO SET NULL;
    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.47';
 */

ALTER TABLE BARN_I_HUSSTAND ALTER COLUMN FOEDSELSDATO SET NOT NULL;








