ALTER TABLE SIVILSTAND
    RENAME COLUMN GYLDIG_FRA_OG_MED TO DATO_FOM;

ALTER TABLE BARN_I_HUSSTAND_PERIODE
    DROP COLUMN BO_STATUS,
    ADD COLUMN BO_STATUS TEXT DEFAULT 'REGISTRERT_PA_ADRESSE';

ALTER TABLE BARN_I_HUSSTAND_PERIODE
    ALTER COLUMN BO_STATUS SET DEFAULT NOT NULL;

DROP TYPE BO_STATUS_TYPE CASCADE;