-- Table: INNTEKT

/*
     ALTER TABLE INNTEKT RENAME COLUMN INNTEKTSTYPE TO INNTEKT_TYPE;

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.40';
 */

ALTER TABLE INNTEKT RENAME COLUMN INNTEKT_TYPE TO INNTEKTSTYPE;






