-- Table: ROLLE

/*
    ALTER TABLE ROLLE RENAME COLUMN OPPRETTET TO OPPRETTET_DATO;
    ALTER TABLE ROLLE ALTER COLUMN OPPRETTET_DATO TYPE DATE;

    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.52';
 */

ALTER TABLE ROLLE RENAME COLUMN OPPRETTET_DATO TO OPPRETTET;
ALTER TABLE ROLLE ALTER COLUMN OPPRETTET TYPE TIMESTAMP;








