-- Table: SIVILSTAND

/*
    UPDATE TABLE SIVILSTAND
        SET KILDE = 'manuelt' WHERE KILDE  = 'MANUELL';
    UPDATE TABLE SIVILSTAND
        SET KILDE = 'offentlig' WHERE KILDE  = 'OFFENTLIG';

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.33';
 */

UPDATE TABLE SIVILSTAND
    SET KILDE = 'MANUELL' WHERE KILDE  = 'manuelt';
UPDATE TABLE SIVILSTAND
    SET KILDE = 'OFFENTLIG' WHERE KILDE  = 'offentlig' OR KILDE IS NULL;




