CREATE TABLE IF NOT EXISTS behandling_data
(
    id                  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    fri_text       text
);

INSERT INTO behandling_data (fri_text) VALUES ('blablabla');