-- Table: SIVILSTAND

/*
    UPDATE SIVILSTAND
        SET KILDE = 'manuelt' WHERE KILDE  = 'MANUELL';
    UPDATE SIVILSTAND
        SET KILDE = 'offentlig' WHERE KILDE  = 'OFFENTLIG';

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.33';
 */

UPDATE SIVILSTAND
    SET KILDE = 'MANUELL' WHERE KILDE  = 'manuelt';
UPDATE SIVILSTAND
    SET KILDE = 'OFFENTLIG' WHERE KILDE  = 'offentlig' OR KILDE IS NULL;




