CREATE TYPE AVSLAG_TYPE AS ENUM
(
    'ANNET_AVSLAG',
    'PGA_BARNEPENSJ',
    'BARNS_EKTESKAP',
    'BARNS_INNTEKT',
    'PGA_YTELSE_FTRL',
    'FULLT_UNDERH_OFF',
    'IKKE_OMSORG',
    'IKKE_OPPH_I_RIKET',
    'MANGL_DOK',
    'PGA_SAMMENFL',
    'OPPH_UTLAND',
    'UTENL_YTELSE'
);

CREATE CAST (VARCHAR AS AVSLAG_TYPE) WITH INOUT AS IMPLICIT;

ALTER TABLE BEHANDLING
    DROP COLUMN AVSLAG,
    ADD COLUMN AVSLAG AVSLAG_TYPE DEFAULT NULL;