-- Table: INNTEKT

/*
     Slettede data må evnt hentes fra backup

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.0.42';
 */

UPDATE INNTEKT SET INNTEKTSTYPE = 'YTELSE_FRA_OFFENTLIG_MANUELT_BEREGNET' WHERE INNTEKTSTYPE = 'YTELSE_FRA_OFFENTLIGE';
UPDATE INNTEKT SET INNTEKTSTYPE = 'LØNNSINNTEKT' WHERE INNTEKTSTYPE = 'LOENNSINNTEKT';







