-- Table: BARNETILLEGG

/* ##### Rulle tilbake ######

    CREATE TABLE IF NOT EXISTS public.barnetillegg
    (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        behandling_id bigint NOT NULL,
        ident text COLLATE pg_catalog."default",
        dato_fom date,
        dato_tom date,
        barnetillegg numeric NOT NULL DEFAULT 0,
        CONSTRAINT barnetillegg_pkey PRIMARY KEY (id),
        CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id)
            REFERENCES public.behandling (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

    ALTER TABLE IF EXISTS public.barnetillegg
        OWNER to "bidrag-behandling-main";

    GRANT ALL ON TABLE public.barnetillegg TO "bidrag-behandling-main";

    GRANT ALL ON TABLE public.barnetillegg TO cloudsqliamuser;

    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.1.3';

 ########*/

DROP TABLE BARNETILLEGG;








