-- Table: UTVIDET_BARNETRYGD

/* ##### Rulle tilbake #####

    -- Table: public.utvidet_barnetrygd

    -- DROP TABLE IF EXISTS public.utvidet_barnetrygd;

    CREATE TABLE IF NOT EXISTS public.utvidet_barnetrygd
    (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        behandling_id bigint NOT NULL,
        delt_bosted boolean,
        dato_fom date,
        dato_tom date,
        belop numeric NOT NULL DEFAULT 0,
        CONSTRAINT utvidetbarnetrygd_pkey PRIMARY KEY (id),
        CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id)
            REFERENCES public.behandling (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

    ALTER TABLE IF EXISTS public.utvidet_barnetrygd
        OWNER to "bidrag-behandling-main";

    GRANT ALL ON TABLE public.utvidet_barnetrygd TO "bidrag-behandling-main";

    GRANT ALL ON TABLE public.utvidet_barnetrygd TO cloudsqliamuser;

     DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.1.4';
 */

DROP TABLE UTVIDET_BARNETRYGD;








