
/**

DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '1.1.2';

*/

INSERT INTO INNTEKT (BEHANDLING_ID, TA_MED, INNTEKTSRAPPORTERING, DATO_FOM, DATO_TOM, IDENT, BELOP, KILDE, GJELDER_BARN)
SELECT B.BEHANDLING_ID, TRUE, 'BARNETILLEGG', B.DATO_FOM, B.DATO_TOM, B.IDENT, B.BARNETILLEGG, 'MANUELL', B.IDENT
FROM BARNETILLEGG B
INNER JOIN ROLLE R ON R.BEHANDLING_ID = B.BEHANDLING_ID
WHERE R.ROLLETYPE = 'BARN';


INSERT INTO INNTEKT (BEHANDLING_ID, TA_MED, INNTEKTSRAPPORTERING, DATO_FOM, DATO_TOM, IDENT, BELOP, KILDE)
SELECT UB.BEHANDLING_ID, TRUE, 'UTVIDET_BARNETRYGD', UB.DATO_FOM, UB.DATO_TOM, R.IDENT, UB.BELOP, 'MANUELL'
FROM UTVIDET_BARNETRYGD UB
INNER JOIN ROLLE R ON R.BEHANDLING_ID = UB.BEHANDLING_ID
WHERE R.ROLLETYPE = 'BIDRAGSMOTTAKER';





