-- TABLE: BEHANDLING

/* ##### RULLE TILBAKE #####

    ALTER TABLE BEHANDLING RENAME COLUMN GRUNNLAG_SIST_KONTROLLERT TO GRUNNLAG_SIST_INNHENTET;
    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '2.0.0';
 */

ALTER TABLE BEHANDLING RENAME COLUMN GRUNNLAG_SIST_INNHENTET TO GRUNNLAG_SIST_KONTROLLERT;
