-- TABLE: GRUNNLAG

/* ##### RULLE TILBAKE #####

    ALTER TABLE GRUNNLAG DROP COLUMN ENDRINGSKONTROLLERT
    DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = '2.0.1';
 */

ALTER TABLE GRUNNLAG ADD COLUMN ENDRINGSKONTROLLERT TIMESTAMP WITHOUT TIME ZONE;
