CREATE TABLE IF NOT EXISTS utgift
(
    id                         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    beløp_direkte_betalt_av_bp bigint not null default 0,
    forrige_historikk          jsonb,
    behandling_id              bigint REFERENCES behandling (id)
);

CREATE TABLE IF NOT EXISTS utgiftspost
(
    id             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    dato           date    not null,
    beskrivelse    text    not null,
    kravbeløp      numeric not null,
    godkjent_beløp numeric not null,
    begrunnelse    text,
    betalt_av_bp   boolean not null default false,
    utgift_id      bigint REFERENCES utgift (id)
);

CREATE INDEX IF NOT EXISTS idx_utgiftspost_utgift_id ON utgiftspost (utgift_id);