create table if not exists person
(
    id bigint primary key generated by default as identity (increment 1 start 1 minvalue 1),
    ident text,
    navn text,
    fødselsdato date,
    opprettet timestamp without time zone
);
