create table if not exists faktisk_tilsynsutgift
(
    id bigint primary key generated by default as identity (increment 1 start 1 minvalue 1),
    underholdskostnad_id bigint not null,
    fom date not null,
    tom date default null,
    tilsynsutgift numeric,
    kostpenger numeric,
    kommentar text,
    constraint fk_underholdskostnad foreign key (underholdskostnad_id) references underholdskostnad(id) match simple
        on update no action
        on delete no action
);
