create table if not exists underholdskostnad
(
    id bigint primary key generated by default as identity (increment 1 start 1 minvalue 1),
    behandling_id bigint,
    person_id bigint,
    har_tilsynsordning boolean,
    foreign key (behandling_id) references behandling(id) match simple
        on update no action
        on delete no action,
    foreign key (person_id) references person(id) match simple
        on update no action
        on delete no action
);