name: Deploy q1
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'

jobs:
  q1:
    name: "Build and deploy to q1"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q1.yaml
  q2:
    name: "Build and deploy to q2"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q2.yaml

