name: Deploy to dev
on:
  workflow_dispatch:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q2.yaml
      maven_options: -B -q -fae -Pit

  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash

    steps:
      - uses: actions/checkout@v4
      - name: Deploy unleash to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash.yaml
          VARS: .nais/main.yaml