name: Deploy to dev
on:
  workflow_dispatch:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]
    branches:
      - '**'
      - '!dependabot/**'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/pr.yaml@main
    secrets: inherit
