name: Deploy to dev
on:
  workflow_dispatch:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: main.yaml
      maven_options: -B -q -fae -Pit

  build-deploy-prod:
    name: "Build and deploy to production"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    with:
      produksjon: true
      nais_variabler_filnavn: prod.yaml
      maven_options: -B -q -fae -Pit
    secrets: inherit
